apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lxd8s.fullname" . }}-preseed
  labels:
    {{- include "lxd8s.labels" . | nindent 4 }}
data:
  {{- with .Values.preseed }}
  preseed.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
