{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "lxd8s.fullname" . }}
  labels:
    {{- include "lxd8s.labels" . | nindent 4 }}
spec:
  routes:
    - match: '{{ include "hostSNI" .Values.ingressRoute.hosts }}'
      services:
        - name: {{ include "lxd8s.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    passthrough: true
{{- end }}
