---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lxd8s.fullname" . }}
  labels:
    {{- include "lxd8s.labels" . | nindent 4 }}
rules:
  - apiGroups: ['']
    resources: ['secrets']
    resourceNames:
      {{- $dot := . }}
      {{- range $i := until (int .Values.certCount) }}
        {{- print "- " (include "lxd8s.fullname" $dot) "-cert-" $i | nindent 6 }}
      {{- end }}
    verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lxd8s.fullname" . }}
  labels:
    {{- include "lxd8s.labels" . | nindent 4 }}
rules:
  - apiGroups: ['discovery.k8s.io']
    resources: ['endpointslices']
    verbs: ['watch', 'list']
