#!/bin/sh

setup() {
    mkdir /proc /sys /dev

    mount -t proc proc /proc
    mount -t sysfs sysfs /sys

    mount -t devtmpfs devtmpfs /dev
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console

    mkdir -p /bin /sbin /usr/bin /usr/sbin
    /bin/busybox --install -s

    mkdir /base /overlay /newroot
}

# Get initramfs working
setup

# Mount the base system (SquashFS)
mount -t squashfs /dev/vda /base

# Set up rw overlay (backed by tmpfs)
mount -t tmpfs tmpfs /overlay
mkdir /overlay/root /overlay/work
mount -t overlay overlay -o lowerdir=/base,upperdir=/overlay/root,workdir=/overlay/work /newroot

exec switch_root /newroot /sbin/init
