name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - charts/**

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      CR_PAT_USER: devplayer0
      REPO: ghcr.io/devplayer0/lxd8s

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.CR_PAT_USER }}
          password: ${{ secrets.CI_PAT }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
          tags: |
            ${{ env.REPO }}:${{ github.sha }}
            ${{ env.REPO }}:latest
          build-args: |
            KERNEL_VERSION=5.4.105
            FIRECRACKER_VERSION=0.24.2
            FIRECTL_VERSION=0.1.3

      # Pushing to an existing tag doesn't seem to work with buildx :(
      - name: Push
        run: docker push "$REPO"
